name: Scala CI

on:
  push:
    branches: [ main ]
    paths:
      - "applications/**"
      - "libs/**"
      - "plugins/**"
      - "build.sbt"
  pull_request:
    branches: [ main ]
    paths:
      - "applications/**"
      - "libs/**"
      - "plugins/**"
      - "build.sbt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout branches
        run: |
          git remote set-branches origin "${{github.base_ref}}" "${{github.head_ref}}"
          git fetch --depth 1
          git checkout "${{github.head_ref}}"

      - uses: stringbean/scalafmt-action@v2
        with:
          use-gitignore: true
          compare-branch: 'origin/${{github.base_ref}}'
  build:
    runs-on: ubuntu-latest
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Setup JDK 13"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17.0.2+8
      - name: "Coursier cache"
        uses: coursier/cache-action@v6
      - name: "Build & Run tests"
        run: sbt -v test
